### PR TITLE
Algalon, fix SPELL_ARRIVAL, fix aggro, fix attack start, also add missing dialogue helper and dialogue step. Fix Living Constellation.

### PR DESCRIPTION
**Pull request by Ulduar**

### CODE REVIEW

**Comment by xfurry** [comment]
Wait... that thing with the Unselectable flag I'm not sure if it's right. I'll have to check the sniff first.

**Comment by Ulduar** [comment]
Sniff lie

**Comment by xfurry** [comment]
Let me know if this https://github.com/scriptdev2/scriptdev2/commit/f575439a377cd7511e70cd8eb3019d47bb894936 fixed the problem.

If not, then I'll try to give it another try and fix it.

**Comment by Ulduar** [comment]
You do not have added all. When he changes aggro flag, then removes it, I proposed a solution, as it can not attack until it this flag when he defeated sets a flag at just reached home changes it. I gave you a video

**Comment by xfurry** [comment]
I have to investigate the not selectable flag change.
As far as I remember in the tankspot and ensidia vids that I saw the flag was not there. But I might be wrong, so I'll check again.

**Comment by xfurry** [comment]
Checked sniff and fixed in https://github.com/scriptdev2/scriptdev2/commit/db23c6e41d84b0f4a51bda1ddc59efd483935fe3

For the achiev spells I have to debug and understand what is the issue.
Most likely it's related to core or DB, because the spell is cast fine in SD2.

**Comment by Ulduar** [comment]
UNIT_FLAG_NOT_SELECTABLE on aggro and remove after Jialogue Step NPC_ALGALON_FIGHT? Missing? Thanks for work. On video has flag.

**Comment by xfurry** [comment]
It has UNIT_FLAG_OOC_NOT_ATTACKABLE in DB and it's removed after SAY_INTRO_3.
This was confirmed by sniff and it works fine.

**Comment by Ulduar** [comment]
I has provided your the video. Where are you sniff come from?

**Comment by xfurry** [comment]
I checked a 4.x sniff. Everything is correct as it is now.

**Comment by Ulduar** [comment]
I play Cataclysm, not Wotlk, and the base is nothing to do with.
On the official server, it changes the flag, then remove and begins to attack. Even on 4.3.4, and even Pandaria Wod.

**Comment by xfurry** [comment]
I don't understand what is the problem...
I told  you that I have a 4.3.4 sniff which I've checked for Algalon and I applied all the flags changes as per the sniff.

The encounter works fine on latest SD2 master and UDB.
The boss won't attack or be attacked during intro or epilogue, which is exactly what you expected and what I see in the vids that you sent.

If there is any issue, different that this, please open a new ticket.

**Comment by Ulduar** [comment]
I can not test unfortunately encounter, because Cataclysm has not been updated for a long time.

**Pull request closed without merging**
