### PR TITLE
Updates for Blackrock Depths

### PR DESCRIPTION
**Pull request by cala**
- Implement missing ambush on Shadowforge Bridge
- Improve Private Rocknot event in Grim Guzzler

### CODE REVIEW

**Comment by xfurry** [comment]
@cala so which commit is ok, and which are you still thinking about it?
Can you show me a video with the event, so I can also understand what are the challenges?

**Comment by cala** [comment]
Hi Xfurry ! :smile:

I'm currently on holidays with my smartphone as the only real link to the Internet, so I can only provide a limited answer, sorry.

I realise that all the comments I made for each commit on my branch were merged by GitHub into the pull request discussion, making them harder to understand. :(

The commit I was refering to is the first one, about the area trigger. It is about two trash NPCs that spawn and move to a specific point when the AT is triggered. The tricks are : the spawned NPCs must change their movement generator from waypoint to random without returning home and there are also plenty of other NPCs with the same entry already spawned on the instance map.
I did it with a mix of SD2 and database (for the waypoints and DBScripts on movement), but I wonder if this could be done in a proper way only with SD2.
You will find more info about this on the related issue. And @Tobschinski can provide more inputs to you, including sniffs. :)

Regarding the other commits, the video links for those are on my computer, so I can't share them right now. But the result in-game with those commits is similar to the video/retail. For me they are ok, but your expert eye might spot code mistakes or missing checks. :smile:
Those commits are for two of the five events taking place in the Grim Guzzler bar. Depending on which event is done by the players, the other ones can be done fully, partially or not at all. 
Currently, only one is basically done in SD2 (Private Rocknot) and I upgraded it to blizzlike in the first part of the Grim Guzzler rework. In the second part of the rework, I added the Hurley Blackbreath event, also blizzlike from sniffs. At least three more commits are coming for the Grim Guzzler when I'm back from holidays: the patrol event, the Nagmara event and the Plugger event. 

I also plan to add more says and yells to Thaurissan fight, but this will be unrelated to the Grim Guzzler rework.

**Comment by xfurry** [comment]
Enjoy your holiday!
We can work on this once you are back.

**Comment by cala** [comment]
Thanks ! Sun, beach and sea food will surely be enjoyable ! :smile:
I'll resume my work on Blackrock Depths when I get back in two weeks and we can discuss this then.

**Comment by cala** [comment]
Hi @xfurry 

I have two more commits coming for this PR once I fixed all the issues that I have on building the core after the recent updates.
Now that SD2 is integrated in the core repository, I would like to know how you want me to proceed:
- create a new PR to cmangos/mangos-woltk based on this one, so we can discuss it
- push everything to cmangos/mangos-woltk since I have also push rights and you can amend/improve the commits if required

Please tell me and I'll do accordingly. :smile:

**Comment by xfurry** [comment]
You can add the new commits to this PR. Once we review and we are fine, you can open a new PR on mangos-wotlk or just push there.
But let's discuss first. :wink:

**Comment by cala** [comment]
Of course ! I'll do so. :smile:

**Comment by cala** [comment]
@xfurry : Here is the last commit for this pull request. Sorry for the delay, I had issues to build the core(s) with all the changes made to it in September.

In a nutshell:
- there are four independent commits [Implement bridge event in Blackrock Depths](https://github.com/cala/scriptdev2/commit/5b30a6ae9fc1359cde67324d184b63c2f0bf549b), [BRD Grim Guzzler rework part 2](https://github.com/cala/scriptdev2/commit/03aafc6fcde5b455e1d294f4505379e4ccd3ce7e), [BRD - Improve Iron Hall encounter](https://github.com/cala/scriptdev2/commit/20b803e5fcc3b517f29f24fb130bcbdc1a8730a4) and [BRD - Improve Emperor Thaurissan encounter](https://github.com/cala/scriptdev2/commit/70d8903af1e85a84d3b826ab11138d40ee99cf1e)
- the other ones are an almost total rework of the Grim Guzzler events and are dependent from each other (using NPC/functions/check introduced in another commit)
- most of those commits are heavily if not 100% based on sniffs, others sources are videos back from Classic

I'm quite happy with almost everything in there (results are very close from what they should be though obviously not 100% perfect). You may probably suggest code improvements or clean up there.
There is also commit [Implement bridge event in Blackrock Depths](https://github.com/cala/scriptdev2/commit/5b30a6ae9fc1359cde67324d184b63c2f0bf549b) that I'd like to discuss with you. The commit mostly works, but I wonder if it could not be done in a cleaner way.

**Comment by xfurry** [comment]
@cala I can see that there are a lot of changes in this PR.
Overall it looks good, so I think you should go ahead and push everything to cmangos master (wotlk).
If there are any minor things that need to be fixed or updated, we can always do it afterwards.

Great job! :+1:

**Comment by cala** [comment]
@xfurry Ok, I'll push them to cmangos core soon. :)

@Tobschinski I think he should have this spell, but we may need to adjust his default damage then. Currently, he hits very hard, especially when the Avatar of Flame is active. With the Ironfoe buff/proc, he would hit like a truck of german trucks and that's extremely hard. I suggest to add the commit as it is and investigate the damage output after.

**Pull request closed without merging**
